version: "3.3"

services:
  tts:
    build: 
      context: ./tts/pytts
    devices:
      - "/dev/snd:/dev/snd"
    ports:
      - "8000:8000"
    environment:
      FLASK_APP: server.py

  rasa_dialog:
    image: rasa/rasa
    build:
      context: ./nlu
    ports:
      - "5005:5005"
  rasa_action:
    build:
      context: ./nlu/actions
    ports:
      - "5055:5055"
  stt:
    build: 
      context: ./stt
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - type: volumes
        source: models
        target: /app/models
        volume:
          nocopy: true

    environment:
      FLASK_APP: server.py
      STT_MODEL_PATH: /app/models/deepspeech-0.9.3-models.pbmm
      WAKE_WORD_MODEL_PATH: /app/models/
  external_services:
    build:
      context: ./services
    ports:
      - "8800:8800"
