version: "3.3"

services:
  tts:
    build: 
      context: ./tts/pytts
    devices:
      - "/dev/snd:/dev/snd"
    ports:
      - "8000:8000"
    environment:
      FLASK_APP: server.py

  rasa_dialog:
    image: rasa/rasa
    ports:
      - "5005:5005"
  rasa_action:
    image: rasa/rasa
    ports:
      - "5055:5055"
  stt:
    build: 
      context: ./stt
    devices:
      - "/dev/snd:/dev/snd"
    environment:
      FLASK_APP: server.py
